### ISSUE TITLE
Inconvenience in debugging with WINIUM

### ISSUE THREAD

**Issue by reshma79** [2gis/Winium.Desktop#106]
Hi,

I am trying to automate desktop application using WINIUM. But it seems very inconvenient while debugging the code. Like for e.g. if my debug point is at following code :

driver.findElement(By.id("123")).click;

Then it click on the code editor in place of clicking on the object. Is there any other way or class which handles / avoids this type of problem?

Any help in solving this would be appreciated.

Regards,
Reshma

**Comment by NickAb** [comment]
We did not tests or try it our selfs, but you can try exploring the following approach:

- If you are using Windows 8.1 you can try using Windows Simulator or RDP into your local machine.
- Run IDE that you use to debug tests on main desktop
- Run driver inside Simulator/RDP

This way driver should stay inside RDP session and move a separate mouse cursor, not affect the focus state of windows, try to click into IDE, etc.

But again, this was not tested, but this is a concept we would like to explore somewhere in the future.

**Comment by skyline-gleb** [comment]
I have nothing new to add, so thank you @NickAb
