### ISSUE TITLE
Element cannot be found message is displayed - Complicated behavior

### ISSUE THREAD

**Issue by muruga85** [2gis/Winium.Desktop#112]
There is a screen in our application where in which the element can be inspected in UIA Verify only when the element is clicked, otherwise its just a pane with no element in it. Is there a way to click the element?

**Comment by NickAb** [comment]
Does element cover all surface of the pane? If so you can try clicking the pane instead, as the driver does not click the element per se, it gets the elements coordinates, moves mouse to that coordinates and clicks. So, if coordinates of element you want to click are the same as coordinates of the pane, it should work.

Alternatively you can get coordinates from the pane, calculate coordinates of the element you want to click, based on known coordinates of pane, and the use action chain to move mouse to that position and click.

**Comment by muruga85** [comment]
The Pane is kind of a gird where in which we enter From Date, To Date, Amount, etc...
So we have around 8 elements within that Pane and all the elements can be inspected only when clicked on it. Please let me know how can we proceed with it.

**Comment by NickAb** [comment]
Can you determine coordinates of elements to be clicked, or maybe elements on a pane, that you click to make inputs (from date, etc) available are themselves are separate elements that can be located by driver?Its hard to make a suggestion without understanding UI tree. If you can, it would be great if you cloud post a partial screenshot of the app and relevant subtree from UISpy, if it is allowed of course.

**Comment by muruga85** [comment]
Yes I can determine the co-ordinates of the element but dont think that will suffice my purpose. The tree Hirerarchy goes like this... Window -> Pane 1--> Pane2.  Editbox ("From Date" etc) are visible under Pane2 in UISpy only when editbox is manually clicked and the Pane2 value is refreshed in UISpy. I hope you can understand my problem now. Kindly advise.

**Comment by skyline-gleb** [comment]
@muruga85 how is it going?

**Comment by muruga85** [comment]
I was actually expecting a solution for the above mentioned scenario. Kindly help.

**Comment by skyline-gleb** [comment]
@muruga85 you can edit code of app or the app not develop now?

**Comment by muruga85** [comment]
The application is already developed and as I explained earlier, that particular element on the window can be inspected only when tabbed to that particular field otherwise we can see only the pane and not the element in it. Please advise

**Comment by muruga85** [comment]
Okay. thank you !! That makes sense
