### ISSUE TITLE
Selenium with Winium: How to get back web driver ref var when we integrate with winium 

### ISSUE THREAD

**Issue by skmvali** [2gis/Winium.Desktop#119]
Steps:

1. Initialize driver ref var for Firefox browser
2. Do some browser actions
3. Reinitialize driver var for Winium driver to handle desktop controls opened from Firefox browser
**4. How to get back Firefox driver var ..so that , easily continue with browser ops**

**Comment by NickAb** [comment]
If I understand correctly, you have a scenario where you have to automate both web elements on a page in the browser and some desktop elements outside of the web page. In that case you can simple use two different variables to store references to selenium driver and winium driver.

```
web_driver = webdriver.Remote(command_executor='http://localhost:4444', desired_capabilities=/*some browser capabilities*/)
app_driver = webdriver.Remote(command_executor='http://localhost:9999', desired_capabilities=/*some winium capabilities*/)

# do stuff in Firefox
web_driver.find_element_by_id(SOME_WEB_ELEMENT_ID).click()

# switch to desktop by simple using app_driver from now on
app_driver.find_element_by_id(SOME_DESKTOP_BUTTON).click()
```

**Comment by skmvali** [comment]
yeah correct..but looking for any winium default lib statement to switch from win ref to web ref once i'm done with win control handling..(Just to clear understanding If u r aware of Selenium RC and WebDriver, we have WebDriverBackedSelenium to switch WebDriver to RC)..If nothing available ..i'll go ahead with above mechanism..Thanks for  the quick response.

**Comment by NickAb** [comment]
Winium and Selenium WebDriver are completely separate processes, so if I understand the case correctly, using two separate variables to hold each driver reference is the only option.

**Comment by skmvali** [comment]
Sure Thanks for the quick reply..i will go ahead with tow ref..

**Comment by muruga85** [comment]
How is it being handled in c#? How to set the capability as winim_capabilities?

**Comment by NickAb** [comment]
Are you asking how to create Winium.Desktop driver/session from test written in C#? If so, here is a simple sample:
```cs
var desiredCapabilities = new DesiredCapabilities();
desiredCapabilities.SetCapability("app", AUT_PATH);

var driver = new RemoteWebDriver(new Uri("http://localhost:9999"), desiredCapabilities);
```

**Comment by muruga85** [comment]
As in your earlier post, it was mentioned as below for Python for switching between the selenium and winium drivers:
web_driver = webdriver.Remote(command_executor='http://localhost:4444', desired_capabilities=WEB_CAPABILITIES)
app_driver = webdriver.Remote(command_executor='http://localhost:9999', desired_capabilities=WINIUM_CAPABILITIES)

How can we achieve the same using c# is my question? 
Also, the reason behind this query was related to my issue logged 10 days ago: 

Title of my open question:
Open question - Winium.Elements.Desktop methods are not being used when remote webdriver is utilitzed

**Comment by NickAb** [comment]
You can have two driver references (one for Winium, one for Selenium) like that:
```
var web_dc = new DesiredCapabilities();
// web_dc.SetCapability(...)
var web_driver = new RemoteWebDriver(new Uri("http://localhost:4444"), web_dc);

var app_dc = new DesiredCapabilities();
app_dc.SetCapability("app", AUT_PATH);

var app_driver = new RemoteWebDriver(new Uri("http://localhost:9999"), app_dc);
```

This will allow you to automate both desktop native app and web app in the browser at the same time.

I am not sure how this is related to #117

**Comment by muruga85** [comment]
Sorry for the confusion. Got the clear picture now and it is not related to #117.  Also, please let me know what has to be passed in the below (...)
web_dc.SetCapability(...) for web drivers. I'm clear that we have to pass app exe in AUT_PATH for app_drivers but wanted to know for web_drivers in specific.

**Comment by sheikhsamina** [comment]
Hii, I am Stuck at scenario where i want to automate chrome browser using winium and than in same browser i want to automate a website using selenium web driver.

**Comment by shekhara-OUP** [comment]
Hi i have to run my code with the help of Jenkins. So some time it happens that system locks down automatically then uploading of file to UI fails as focus from application shifts. So can we upload a file to UI even if focus shifts or system lock down with the help of winium

**Comment by Djunifive** [comment]
Hello Guys,

How can I do this with Java code?

Thank you for the assistance.

**Comment by BgopikrishnaSabbineni** [comment]
> You can have two driver references (one for Winium, one for Selenium) like that:
> 
> ```
> var web_dc = new DesiredCapabilities();
> // web_dc.SetCapability(...)
> var web_driver = new RemoteWebDriver(new Uri("http://localhost:4444"), web_dc);
> 
> var app_dc = new DesiredCapabilities();
> app_dc.SetCapability("app", AUT_PATH);
> 
> var app_driver = new RemoteWebDriver(new Uri("http://localhost:9999"), app_dc);
> ```
> 
> This will allow you to automate both desktop native app and web app in the browser at the same time.
> 
> I am not sure how this is related to #117

ca

> You can have two driver references (one for Winium, one for Selenium) like that:
> 
> ```
> var web_dc = new DesiredCapabilities();
> // web_dc.SetCapability(...)
> var web_driver = new RemoteWebDriver(new Uri("http://localhost:4444"), web_dc);
> 
> var app_dc = new DesiredCapabilities();
> app_dc.SetCapability("app", AUT_PATH);
> 
> var app_driver = new RemoteWebDriver(new Uri("http://localhost:9999"), app_dc);
> ```
> 
> This will allow you to automate both desktop native app and web app in the browser at the same time.
> 
> I am not sure how this is related to #117

how can we do with java code?

**Comment by BgopikrishnaSabbineni** [comment]
> If I understand correctly, you have a scenario where you have to automate both web elements on a page in the browser and some desktop elements outside of the web page. In that case you can simple use two different variables to store references to selenium driver and winium driver.
> 
> ```
> web_driver = webdriver.Remote(command_executor='http://localhost:4444', desired_capabilities=WEB_CAPABILITIES)
> app_driver = webdriver.Remote(command_executor='http://localhost:9999', desired_capabilities=WINIUM_CAPABILITIES)
> 
> # do stuff in Firefox
> web_driver.find_element_by_id(SOME_WEB_ELEMENT_ID).click()
> 
> # switch to desktop by simple using app_driver from now on
> app_driver.find_element_by_id(SOME_DESKTOP_BUTTON).click()
> ```

I tried with Java, but not winium driver not doing any thing
