### ISSUE TITLE
Unable to test any application

### ISSUE THREAD

**Issue by FROSADO** [2gis/Winium.Desktop#121]
All tests using Winium.Desktop and Python selenium is failing : 
C:\path>Winium.Desktop.Driver.exe --verbose
```
Starting Windows Desktop Driver on port 9999
18:25:55 [DEBUG] Waiting for a connection...
18:25:59 [DEBUG] ACCEPTED REQUEST
18:25:59 [FATAL] Failed to start driver: System.NullReferenceException: Object reference not set to an instance of an object.
   at Winium.Desktop.Driver.Listener.HandleRequest(HttpRequest acceptedRequest)
   at Winium.Desktop.Driver.Listener.StartListening()
   at Winium.Desktop.Driver.Program.Main(String[] args)

Unhandled Exception: System.NullReferenceException: Object reference not set toan instance of an object.
   at Winium.Desktop.Driver.Listener.HandleRequest(HttpRequest acceptedRequest)
   at Winium.Desktop.Driver.Listener.StartListening()
   at Winium.Desktop.Driver.Program.Main(String[] args)
```
The code failed directly when i'm trying to start the driver : 
````python
from selenium import webdriver
driver = webdriver.Remote(
    command_executor='http://localhost:9999',
    desired_capabilities={
       "app": r"C:/windows/system32/calc.exe"
    })
```
I have installed .Net version  4.6.01055, could be this the problem?

**Comment by NickAb** [comment]
What version of Selenium bindings do you use? I think there was a similar problem when using newer bindings.

**Comment by NickAb** [comment]
I've tested driver against python bindings. selenium==2.45.0 works fine, selenium==2.53.6 breaks driver as it receives empty request.

Current workaround is to try downgrading appium or selenium bindings being used.

**Comment by skyline-gleb** [comment]
@NickAb Thank you for your testing.
I created bug issue #122 for resolve this problem.

**Comment by skyline-gleb** [comment]
True from 2.53.3 version python bindings (current versions is 2.53.6/3.0.0b3 with this problem).
With .net bindings works fine (current versions is 2.53.1/3.0.0-beta3)

**Comment by anileapencylon** [comment]
Hi,

I am running few test using Winium . For some reason after running the test my application (.exe) that I am using crashes. So I can't continue the test. Could someone provide some ideas please.
Thanks

**Comment by anileapencylon** [comment]
Forgot to mention I am also using Extent Reports in Visual studio.
I am using the below:
[OneTimeSetUp]
public void BeforeClass()
{
try
{
//To create report directory and add HTML report into it

            extent = new ExtentReports();
            var dir = AppDomain.CurrentDomain.BaseDirectory.Replace("\\bin\\Debug", "");
            DirectoryInfo di = Directory.CreateDirectory(dir + "\\Test_Execution_Reports");
            var htmlReporter = new ExtentHtmlReporter(dir + "\\Test_Execution_Reports" + "\\Automation_Report" + ".html");
            extent.AddSystemInfo("Application", "CXPro 1.01B351");
            extent.AddSystemInfo("User Name", "Product Development");
            extent.AttachReporter(htmlReporter);
        }
        catch (Exception e)
        {
            throw (e);
        }

        try
        {
            var service = WiniumDriverService.CreateDesktopService(@"C:\Users\anil.Pallithekethil\Downloads\Winium.Desktop.Driver");
            var options = new DesktopOptions { ApplicationPath = @"C:\CXpro101324\Port32Ex.exe" };
            driver = new WiniumDriver(service, options);

            Thread.Sleep(5000);

           // driver.FindElementByName("OK").Click();
        }
        catch (Exception e)
        {
            throw (e);
        }
    }
