### ISSUE TITLE
Question - How to find the elements of the window

### ISSUE THREAD

**Issue by tkuben** [2gis/Winium.Desktop#136]
Hi, 

I am trying to test a windows based application in python. The application comes up, but how do you find out the elements to send text or to click etc? I do not know the id's names or classes etc. Thoughts? When I inspect the elements by running driver.find_elements(), I only have the id but do know know which element it is... 

```
from selenium import webdriver

driver = webdriver.Remote(command_executor='http://localhost:9999',
                               desired_capabilities={'app': 'C:\\Program Files (x86)\\Software\\gui.exe',
                                                     })
elements = driver.find_elements()
for ele in elements:
    print ele
```

Cheers, 
TJ

**Comment by NickAb** [comment]
You can use Microsoft provided UI verification and inspection tools like UIA Verify, Inspect or UISpy (obsolete). Please read more on this tools at https://msdn.microsoft.com/en-us/library/dd373661(v=vs.110).aspx

**Comment by tkuben** [comment]
I ended up using: https://github.com/2gis/Winium.Cruciatus/tree/master/tools/UISpy

Works great! 
Cheers,

**Comment by bernd-wechner** [comment]
Alas this doesn't really answer the question. This method is fine and I use it admirably. BUt i'm having trouble using Winium to find those elements and want to ask Winium what elements it sees, not what elements another tool sees. And Winium surely needs/has a method of fecthing the list/tree (large as it may be) of UI elements it sees?
