### ISSUE TITLE
How to attach to running application?

### ISSUE THREAD

**Issue by lizaolaa** [2gis/Winium.Desktop#139]
There is no way to attached the Winium driver to an already open application.

**Comment by NickAb** [comment]
You can set `debugConnectToRunningApp` capability to `true` and provide any valid app path in `app` capability.
This will result in driver creating new session, but not starting any application automatically. After that you can use `FindElement` command to find a window or any elements of already running application you want to test.

**Comment by NickAb** [comment]
@lizaolaa did it work for you?

**Comment by lizaolaa** [comment]
Yes, it works but then there are many problems to detect elements. There is
not enough information or help

**Comment by NickAb** [comment]
I am closing this issue. Please file any problems with locating elements in a new issue with detailed description.
