### ISSUE TITLE
system.argumentException: LayoutRenderer cannot be found: longdate

### ISSUE THREAD

**Issue by ppaso007** [2gis/Winium.Desktop#140]
Unable to run Winium Driver in windows 7. Getting this exception.

![image](https://cloud.githubusercontent.com/assets/17878552/21378230/d8f140da-c76a-11e6-8960-b132f747547a.png)

**Comment by gunaphysics** [comment]
Try updating your .NET Framework to the latest version

**Comment by NickAb** [comment]
Please upgrade .NET Framework to 4.5.1

Dup of #118
