### ISSUE TITLE
Get attribute that contains space in its name

### ISSUE THREAD

**Issue by OtherVibes** [2gis/Winium.Desktop#145]
Hello,
I'm trying to get_attribute() of element that contains space ("Bounding rectangle").
The get_attribute function returns None and I suspect that it is related to the fact that it contains space.

Thanks,
hepivax

**Comment by heilwood** [comment]
Other attributes with no space from such element you can get without problems?

**Comment by Faresbrahem** [comment]
@heilwood  i have the same  problem and yes i can get other attributes without problems

**Comment by heilwood** [comment]
@Faresbrahem what type of attribute you trying to get? Name or something else?

**Comment by OtherVibes** [comment]
The "Name" attribute is a single word attribute and therefore it doesn't contain any spaces. 
I meant to attributes that contains two words like "Class Name" or "Bounding Rectangle".
I will really appriciate if if someone could give me a solution, the "Class Name" for example is extremely useful to recognize control types.

**Comment by heilwood** [comment]
@hepivax i'm using ui verify tool for inspecting elements and in this tool this attributes i see as one word without spaces, try to get this attribute like this "ClassName", for me working fine
