### ISSUE TITLE
unable to find element that can be detected in Snoop WPF Spy

### ISSUE THREAD

**Issue by OtherVibes** [2gis/Winium.Desktop#147]
Hello,
I'm trying to locate some element that can be easily located using [Snoop](https://github.com/cplotts/snoopwpf) but cannot be located by AutomationSpy.
I tried to locate the element by both its name & class using Winium without success.
The main problem is that I cannot explain to the RnD owner what's missing or name the problem in the AUT and what need to be done in order to expose this element.

Your help is much appreciated,
hepivax

**Comment by heilwood** [comment]
Are you sure that you don't have another element with the same ClassName or Name?
