### ISSUE TITLE
FindElementByName does not identify all the elements with 'same name' under the tree

### ISSUE THREAD

**Issue by SharonJacob** [2gis/Winium.Desktop#148]
Hi I'm using Winium to test my application. The application has a navigation tab nad 4 elements witht he name "Worklists". One of them has the Control type button.
I used FindElement(By.Name("Worklists").AndType(ControlType.Button)) but, failed to identify the element.

I also used FindElementsByName("Worklists"). This line only captures the first three elemets and not the button.

Any idea how to navigate to the button element??

Below is the tree structure, worklist button attributes and snippet of C# code

![worklist](https://cloud.githubusercontent.com/assets/22199830/22759054/14ce30c4-ee1f-11e6-9411-97321b6f1059.png)

![worklistbutton](https://cloud.githubusercontent.com/assets/22199830/22759280/d7fa4cc2-ee1f-11e6-93b5-3c1737be0212.png)

![c snippet](https://cloud.githubusercontent.com/assets/22199830/22759303/f0e5f16e-ee1f-11e6-8bf0-c82a431d7605.png)

**Comment by OtherVibes** [comment]
I would try to findElements by the following xpath:
//NavigationGroup/Worklists
and get the second element from the list.

**Comment by SharonJacob** [comment]
I tried all the possible ways to get there. the UI Spy is not able to locate the element. Looks like there is no way to get there. I'm using Sikuli and images to get there!! This is the solution i found for now

**Comment by Sourabh25** [comment]
Did you get the answer to this question?

**Comment by SharonJacob** [comment]
Yes, I used UI Automation Client.dll

**Comment by Sourabh25** [comment]
I have an object with hierarchy : Window->Pane->Edit. This information I got by using UIspy.
Could you please tell me , how i can use findElement to add this object and use winium webdriver

**Comment by SharonJacob** [comment]
Did you get through this? 

If not, please provide screen shot of the tree

**Comment by Sourabh25** [comment]
No it is not resolved. Please find attached screenshot
![screenshot](https://cloud.githubusercontent.com/assets/18703893/23921702/ffff47f6-08d5-11e7-83e1-75971aad78db.jpg)

**Comment by SharonJacob** [comment]
Are you doing it with java or C#?

Also, I need you you to capture screenshot with focus on Data support system and also Pane, that I can see their attributes

**Comment by Sourabh25** [comment]
I am using java. Please find attached the files.

![screenshot3](https://cloud.githubusercontent.com/assets/18703893/23927132/6ee950f4-08ee-11e7-884b-61f7ec4ce39a.jpg)
![screenshot2](https://cloud.githubusercontent.com/assets/18703893/23927133/6eed5780-08ee-11e7-84c6-8dbb3e1bd435.jpg)

**Comment by SharonJacob** [comment]
If the driver is working well and you are able to launch the application with winium driver.
Below code should works well with C#, you can try changing the syntax for java environment.

var  winMain = Winium.Cruciatus.CruciatusFactory.Root.FindElement(By.Id("frmLogin"));
var winPane = winMain.FindElementByUid("GradientPanel1");
var username = winPane.FindElementByUid("txtUser");

Assuming you are trying to send text to this field.
username.click();
username.SetText("xxxxx");

**Comment by Sourabh25** [comment]
Thanks... this is working. :) Thank you so much

**Comment by SharonJacob** [comment]
You're welcome

**Comment by Sourabh25** [comment]
Hi,

I want to know how can i change the hierarchy of the Winium driver, Suppose I have a screen with window w1 - pane p1 - login screens. after entering credential, the application loads and window changed to W2. Now my driver should point to Widow w2- pane P2 - Home Page. 

Thanks,
Sourabh

**Comment by nikita1307** [comment]
Hello,

I am also facing a similar issue while using winium driver. Not able to identify the elements inside a pane. Also, when I open the DOM for the page, I can see an html tag of "iframe" in which elements are present.
Can anyone please tell that from where can I get UI Automation Client.dll and how to use it. we have tried lot many property value pairs and also ancestors and siblings in the xpath. Nothing seems to be working.

**Comment by bindupatnaik** [comment]
@SharonJacob how did u fix this problem as i m facing similar issue using Winium. It is not able to identify a Tree item of Device manager on win10 machine. Any kind of help is much appreciated.

**Comment by Sourabh25** [comment]
@bindupatnaik Could you please mention what you have done and where you having the issue?

**Comment by pradideepu1992** [comment]
hi @SharonJacob  , 

Am using Winium with C# in Visual studio , I have an windows application built using both (WCF and WPF components) . I need to click on several button present under group . Can u please let me know best to way to handle it .

![image](https://user-images.githubusercontent.com/85234238/120482328-a5f66600-c3ce-11eb-9221-ef91cf3e3d6d.png)


Under Config Group , i have around 7 buttons to click and Non config group 3 more button present in UI
