### ISSUE TITLE
getScreenshotAs() from WebElement is not supported

### ISSUE THREAD

**Issue by OtherVibes** [2gis/Winium.Desktop#149]
I'm trying to use the following code:
`File screenshot = webElement.getScreenshotAs(OutputType.FILE);`
 
and getting the following exception as a result:

`org.openqa.selenium.UnsupportedCommandException: Unknown command http://localhost:9999/session/AwesomeSession/screenshot/60500830-3
Command duration or timeout: 16 milliseconds
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'MyHost', ip: '10.10.10.10', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_67'
Session ID: AwesomeSession
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities [{debugConnectToRunningApp=false, app=C:\MyApp.exe, platform=ANY, launchDelay=0, innerPort=9998, args=, keyboardSimulator=1}]
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.lang.reflect.Constructor.newInstance(Unknown Source)
at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:327)
at org.openqa.selenium.remote.RemoteWebElement.getScreenshotAs(RemoteWebElement.java:447)`

I have **no problem** to take screenshot from a`RemoteWebDriver` object.
This functionality is required as in some parts of our code we're calling static `takeScreenhot()` method that can get only `WebElement` as the `RemoteWebDriver`  is unknown.

**Comment by heilwood** [comment]
i'm using custom screenshot getter, because winium screenshot implementation, taking full desktop screenshot, im getting screenshots for application only.

**Comment by SanjeevKumarmn** [comment]
here is my code--
`   public void take_screenshot(){
        String base64Screenshot = driver.getScreenshotAs(OutputType.BASE64);
        byte[] decodeScreenshot = Base64.decodeBase64(base64Screenshot.getBytes());
        scenario.embed(decodeScreenshot, "image/png");
    }`

I was also looking for screenshot only for specific element which seems to be not working and here is the code -

`public void take_screenshot_element(WebElement element) {
        final BufferedImage img ;
        final Point topleft;
        final Point bottomright;
        final byte[] screengrab;
        byte[] imageInByte = new byte[0];
        BufferedImage image_byte;
        screengrab = ((TakesScreenshot) driver).getScreenshotAs(OutputType.BYTES);
        try {
            img = ImageIO.read(new ByteArrayInputStream(screengrab));
            topleft = element.getLocation();
            bottomright = new Point(element.getSize().getWidth(),element.getSize().getHeight());
            image_byte = img.getSubimage(topleft.getX(),topleft.getY(),bottomright.getX(),bottomright.getY());
            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            try {
                ImageIO.write( image_byte, "jpg", baos );
                baos.flush();
                imageInByte = baos.toByteArray();
                baos.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        byte[] decodeScreenshot = Base64.decodeBase64(imageInByte);
        scenario.embed(decodeScreenshot, "image/png");
    }`

Error info: org.openqa.selenium.UnsupportedCommandException: 'getElementLocation' is not valid or implemented command. (WARNING: The server did not provide any stacktrace information)
