### ISSUE TITLE
WPF / Textblock / get text

### ISSUE THREAD

**Issue by CyrilJ** [2gis/Winium.Desktop#151]
Hello,

I'm not able to get the Text of the textblock.

I was expecting to write a test like this :
```c#
var element = DriverHolder.Driver.FindElementById("LoginUtilisateur");      
Assert.AreEqual(loginText, element.Text);
```

But i need to do this :
```c#
var element = DriverHolder.Driver.FindElementByName(loginText);
Assert.IsNotNull(element);
```

I found the reason on stackoverflow : 
[http://stackoverflow.com/questions/1676266/silverlight-ui-automation-of-a-textblock](url)

Windows automation put Text in the name of the texblock.

I don't know if you have to modify Cruciatus or Desktop to do this.
You can consider this issue as an improvement since this is the default behavior, but it will be much better if the command Text() works with TextBlock.

Thanks

**Comment by stanjer** [comment]
Same for me. After a couple hours of struggle, I wasn't able to find any way of getting text from `TextBox`. There are no any accessible properties with field's text, except `Value.Value` and `LegacyIAccessible.Value` (as seen from Inspector), which are both not accessible by get_property function (I'm using python).

Asking for another possible question - `element.text` doesn't work as well and returns:
```
 selenium.common.exceptions.WebDriverException: Message: NO GET TEXT
```
Here is element's properties returned by Inspector:
```

```

Is there anything else I can try?

**Comment by ShreyasPatil** [comment]
I am also facing same issue, I am not able to get text of element. Getting following error : 
`NO GET TEXT (Selenium::WebDriver::Error::UnknownError)`

Code using Ruby
`ele = $driver.find_element(:id, "65535")`
`puts ele.text`

Element properties are as follows
```AutomationElement
  General Accessibility
    AccessKey:	""
    AcceleratorKey:	""
    IsKeyboardFocusable:	"False"
    LabeledBy:	"(null)"
    HelpText:	""

  State
    IsEnabled:	"True"
    HasKeyboardFocus:	"False"

  Identification
    ClassName:	"Static"
    ControlType:	"ControlType.Text"
    Culture:	"(null)"
    AutomationId:	"65535"
    LocalizedControlType:	"text"
    Name:	"Username or Password should not be blank."
    ProcessId:	"14480 (RetailMantra)"
    RuntimeId:	"42 657448"
    IsPassword:	"False"
    IsControlElement:	"True"
    IsContentElement:	"False"

  Visibility
    BoundingRectangle:	"(584, 369, 233, 17)"
    ClickablePoint:	"700,377"
    IsOffscreen:	"False"

**Comment by heilwood** [comment]
You can get attribute name using GetAttribute method.

var element = DriverHolder.Driver.FindElementById("LoginUtilisateur");      
Assert.AreEqual(loginText, element.GetAttribute("Name"));

But in my case everything working fine using element.Text.

**Comment by CyrilJ** [comment]
Your alternative works like a charm. 
I close the issue.
