### ISSUE TITLE
how to run winium driver in a framework

### ISSUE THREAD

**Issue by Sourabh25** [2gis/Winium.Desktop#158]
Hi,

I would like to set up an automation framework using Winium webdriver. Hence i don't to explicitly start the winium.desktop.webdriver.exe. I am using java. Could someone please help how can i achieve that?

**Comment by muruga85** [comment]
This is what I've used for C#. Just place the driver in the specified local drive and launch the application as below:

public static DesktopOptions options = new DesktopOptions { ApplicationPath = @".exe path" };
public static WiniumDriverService service = WiniumDriverService.CreateDesktopService(@"D:\Driver");
public static WiniumDriver driver = new WiniumDriver(service, options);

**Comment by Sourabh25** [comment]
okay thanks.. this helps

**Comment by PraveenITT** [comment]
What if I have to start three application one after another?
