### ISSUE TITLE
Drag and drop is not working for me

### ISSUE THREAD

**Issue by heilwood** [2gis/Winium.Desktop#162]
Hi, drag and drop from actions is not working for me i get such exception: "Result Message:	'mouseDown' is not valid or implemented command."   

My function looks like this:
public void DragAndDrop(By elemToDrag, By elem)
        {
            WaitUntilElementIsVisible(elemToDrag);
            var elemToDrag = MainWindow().FindElement(elemToDrag);
            var elOn = MainWindow().FindElement(elem);
            var action = new Actions(_driver);
            action.DragAndDrop(elemToDrag, elOn).Perform();
        }

Can you tell me please where can be mistake?

**Comment by heilwood** [comment]
Functionality was not added to source control, project has been build locally with added DragAndDrop functionality, everything working fine.

**Comment by OtherVibes** [comment]
@heilwood how can I use the actions drag and drop? Do you have plans to commit?

**Comment by truptibhatt** [comment]
@heilwood - is drag and drop working in winium desktop driver?

**Comment by heilwood** [comment]
@hepivax @truptibhatt Drag and drop is working but is not added to latest version, if you would like to have version with drag and drop, email me and i will send you.

**Comment by truptibhatt** [comment]
@hepivax - Can you share your email id?

**Comment by heilwood** [comment]
I think the last message was for me, you can download my version of winium here http://www.mediafire.com/file/7ikkxqvgilkr6jk/Winium.Desktop.Driver.exe.7z/file , improved performance, support for node hub has been added, drag and drop, selenium Keys are working fine, driver quit for click once app has been added, but you need to launch winium driver using this command: 

            var options = new DesktopOptions
            {
                ApplicationPath = PathToYourApplicationString,
                KeyboardSimulator = KeyboardSimulatorType.BasedOnWindowsFormsSendKeysClass
            };
            _driver = new WiniumDriver(pathToWiniumDriver, options);

**Comment by shivalkar** [comment]
Hello @heilwood can you please share the code with me?

**Comment by bryanvaldellon** [comment]
> @hepivax @truptibhatt Drag and drop is working but is not added to latest version, if you would like to have version with drag and drop, email me and i will send you.

Hi @heilwood can I have a copy too? thanks!

**Comment by sudeeppaudyal** [comment]
System.NotImplementedException: ''getElementTagName' is not valid or implemented command.'
 
I am trying to use Select class to get element from combo box getting execption.Pleasa help.
SelectElement oSelection = new SelectElement(driver.FindElementById("15"));

**Comment by heilwood** [comment]
Heilwood@inbox.lv write me on email i will send you version with drag and drop

**Comment by bryanvaldellon** [comment]
> Heilwood@inbox.lv write me on email i will send you version with drag and drop

Emailed you. Thanks!

**Comment by nvahao** [comment]
Hi heilwood,
Could you help me with that version which drag and drop is implemented ?
check my email h.zenku@gmail.com

**Comment by javawinium** [comment]
HI , i am also facing the similar kind of issue , could someone help me on this 

while using drag& drop in my desktop application  , getting following error 



Exception in thread "main" org.openqa.selenium.UnsupportedCommandException: 'mouseDown' is not valid or implemented command. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 31 milliseconds
Build info: version: '2.48.2', revision: '41bccdd10cf2c0560f637404c2d96164b67d9d67', time: '2015-10-09 13:08:06'
System info: host: 'mccukswtstdc01', ip: '192.168.97.38', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.7'
Driver info: org.openqa.selenium.winium.WiniumDriver
Capabilities [{app=C:\IPR\Intergraph.Pr.Cockpit.exe, args=, innerPort=9998, debugConnectToRunningApp=false, keyboardSimulator=1, launchDelay=0, platform=ANY}]
Session ID: AwesomeSession
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:647)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:670)
	at org.openqa.selenium.remote.RemoteExecuteMethod.execute(RemoteExecuteMethod.java:33)
	at org.openqa.selenium.remote.RemoteMouse.mouseDown(RemoteMouse.java:77)
	at org.openqa.selenium.interactions.ClickAndHoldAction.perform(ClickAndHoldAction.java:42)
	at org.openqa.selenium.interactions.CompositeAction.perform(CompositeAction.java:50)
	at OPRTest.OrgChart.main(OrgChart.java:67)

**Comment by yatendra99** [comment]
Hi heilwood,
Could you help me with that version which drag and drop is implemented ?
My Email ID is r.yatendrak@gmail.com

**Comment by ksuhasinik** [comment]
Hi Heliwood, 
Could you help me with that version which drag and drop is implemented?
My Email ID is suhasinikuruba@gmail.com

**Comment by anileapen** [comment]
Hi Heilwood,

Could I also get the details of how to implement drag and drop please? I wanted to add that to my Winium scripts. My email is anileapen_99@hotmail.com
Thanks 
Anil

**Comment by bndnkumari453** [comment]
Hi @heilwood , Could you please share the code with me ? My emailid - bndnkumari453@gmail.com

**Comment by Drewski-123** [comment]
Hello @heilwood  Are you still emailing people the version with working drag and drop? If so my email is drew.gitlin@wesuite.com
Thank you!

**Comment by satisht1** [comment]
Hello All,

Were you able to perform Drag and drop with the new version? 

@Drewski-123 @bndnkumari453 @anileapen @yatendra99

**Comment by JanosHatvani** [comment]
Hi Heilwood!
Could you help me with that version which drag and drop is implemented ?
My email is : hatvanijn@gmail.com

Thank you!
Jani
