### ISSUE TITLE
Do we have any default winium methods available for Ruby language?

### ISSUE THREAD

**Issue by rajasekharchellapandi** [2gis/Winium.Desktop#165]
I would like to know is there any default winium scripts are available or not for ruby language? 

![image](https://cloud.githubusercontent.com/assets/27760982/25213591/4885d9a4-25af-11e7-8c32-baa29496ceaa.png)

**Comment by heilwood** [comment]
Winium.Desktop is just .exe file which can work with selenium as driver. Doesn't matter which programming language you are using.

**Comment by rajasekharchellapandi** [comment]
Hi @heilwood ,
Do you have any code to invoke windows application in ruby language? If yes, can you please provide the sample code to me.

**Comment by viveksgit** [comment]
require 'selenium-webdriver'
require 'rubygems'
class WiniumTest
  def launchApplication
    caps = Selenium::WebDriver::Remote::Capabilities.new
    caps['app'] = 'C:/windows/system32/calc.exe'
    driver = Selenium::WebDriver.for :remote, url: "http://localhost:9999", desired_capabilities: caps
  end
end

Test = WiniumTest.new
Test.launchApplication

**Comment by rajasekharchellapandi** [comment]
Thank you @viveksgit !!

**Comment by sidigum** [comment]
@viveksgit : Thanks for you sample code. Could you give some sample lines of code to enter values in calculator

**Comment by harimadusumilli** [comment]
caps = Selenium::WebDriver::Remote::Capabilities.new
    caps['app'] = 'C:/windows/system32/calc.exe'
	driver = Selenium::WebDriver.for :remote, url: "http://localhost:9999", desired_capabilities: caps

calc = driver.find_element(:class_name =>'CalcFrame')
calc.find_element(:name => "1").click # Clicks Button 1
calc.find_element(:name => 'Add').click # Clicks the "+"
calc.find_element(:name => "2").click  #Clicks Number 2 
calc.find_element(:name => "Equals").click # clicks equal sign "="

#Try the above, it should work
