### ISSUE TITLE
Magic Samples displays an error in the execution

### ISSUE THREAD

**Issue by paulofachini** [2gis/Winium.Desktop#166]
Executing the example "[Magic Samples](https://github.com/2gis/Winium.Desktop/wiki/Magic-Samples#c)" the error below is displayed.
NuGet installed:
- Selenium.WebDriver: v3.4.0
- Winium.WebDriver: v0.1.1

Error message:
OpenQA.Selenium.WebDriverException was unhandled
  HResult=-2146233088
  Message=The HTTP request to the remote WebDriver server for URL http://localhost:9999/session/AwesomeSession/element timed out after 60 seconds.
  Source=WebDriver
  StackTrace:
       em OpenQA.Selenium.Remote.HttpCommandExecutor.CreateResponse(WebRequest request)
       em OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
       em OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
       em OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(String mechanism, String value)
       em OpenQA.Selenium.Remote.RemoteWebDriver.FindElementByClassName(String className)
       em ConsoleApplication.Program.Main(String[] args) na C:\Benner\Fontes\ConsoleApplication\ConsoleApplication\Program.cs:linha 16
       em System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       em System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       em Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       em System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       em System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       em System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       em System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       em System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
       HResult=-2146233079
       Message=O tempo limite da operação foi atingido
       Source=System
       StackTrace:
            em System.Net.HttpWebRequest.GetResponse()
            em OpenQA.Selenium.Remote.HttpCommandExecutor.CreateResponse(WebRequest request)
       InnerException:

**Comment by heilwood** [comment]
Here can be several issues, if this timeout happen on first command execution, you can try to close all applications (in my case it was chrome and SQL manager), also can help PC restart and Winium.Desktop should be launched as administrator.

**Comment by heilwood** [comment]
Also this repository for Winium Desktop, i'm not sure that nuget package is the same, first of all download manually binary Winium.Desktop from this repositoy, run this app as administrator, then try to execute your tests. Winium.WebDriver from NuGet not needed for tests execution.

**Comment by paulofachini** [comment]
Thank you for your help.
But it only worked when I replaced the code:
```
var dc = new DesiredCapabilities();
dc.SetCapability("app", @"C:/windows/system32/calc1.exe");
var driver = new RemoteWebDriver(new Uri("http://localhost:9999"), dc);
```
By code:
```
DesktopOptions deskopts = new DesktopOptions();
deskopts.ApplicationPath = "C:\\windows\\system32\\calc.exe";
string directory= "C:\\Winium";
WiniumDriver driver = new WiniumDriver(winiumDriverDirectory: directory, options: deskopts);
```

**Comment by heilwood** [comment]
In your first example you trying to launch calc1.exe instead of calc.exe :) In my case everything works fine with your first example
