### ISSUE TITLE
How to make Winium.Desktop.Driver start in different port than 9999?

### ISSUE THREAD

**Issue by Bala810R** [2gis/Winium.Desktop#170]
When running Winium.Desktop.Driver we get a message "Starting Windows Desktop Driver on port 9999". Is there a way to make it run in different port?  My scenario is that we have a remote server which allows multiple user logins at the same time, and we want all users to run Winium test by using different ports

**Comment by K1ryl** [comment]
Winium.Desktop.Driver.exe --port "port"

**Comment by Bala810R** [comment]
Thank you for the response, however when I try that the driver still starts at 9999.  Also I assume we must be allowed to run the driver as many time we want simultaneously.  Because based on my understanding the .exe should find free port that is available and should run on it.  However when we try to run two instance of the driver in same machine, first instance works and second gets error.

23:40:10 [FATAL] Failed to start driver: System.Net.Sockets.SocketException (0x8
0004005): Only one usage of each socket address (protocol/network address/port)
is normally permitted
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress
socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at System.Net.Sockets.TcpListener.Start(Int32 backlog)
   at Winium.Desktop.Driver.Listener.StartListening()
   at Winium.Desktop.Driver.Program.Main(String[] args)

Unhandled Exception: System.Net.Sockets.SocketException: Only one usage of each
socket address (protocol/network address/port) is normally permitted
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress
socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at System.Net.Sockets.TcpListener.Start(Int32 backlog)
   at Winium.Desktop.Driver.Listener.StartListening()
   at Winium.Desktop.Driver.Program.Main(String[] args)

**Comment by shmarlovski** [comment]
I'm using v1.6.0 and it allows to use different ports. 
`Winium.Desktop.Driver.exe --port 8888`
`Winium.Desktop.Driver.exe --port 4545`
etc..

I don't agree that .exe should find any free port and listen to it. In that case we don't know which port to connect.
9999 - default one. If you want another - just specify it. If you want several connections - start several instances of Winium.

The error you see it's unhandled exception, it's a bug.

**Comment by K1ryl** [comment]
I'm using v1.6.0 and it allows to use different ports. 
`Winium.Desktop.Driver.exe --port 8888`
`Winium.Desktop.Driver.exe --port 4545`
etc..

I don't agree that .exe should find any free port and listen to it. In that case we don't know which port to connect.
9999 - default one. If you want another - just specify it. If you want several connections - start several instances of Winium.

The error you see it's unhandled exception, it's a bug.

**Comment by Bala810R** [comment]
Thank you update.  yes, it does work for me too.  I made some mistake in syntax of my .exe trigger.

**Comment by vidhijain11** [comment]
How to make setting to use port -- 8888 and 4545
Using  --
WiniumDriverService service = new WiniumDriverService.Builder().usingDriverExecutable(drivePath).usingPort(8888).withVerbose(true).withSilent(false).buildDesktopService(); 
			service.start();
			driver = new WiniumDriver(new URL("http://localhost:8888"), options);
			 driver = new WiniumDriver(service, options);

But getting error - 

	Starting Windows Desktop Driver on port 9999

08:07:50 [ERROR] SocketException occurred while trying to start listner: System.Net.Sockets.SocketException (0x80004005): Only one usage of each socket address (protocol/network address/port) is normally permitted
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at System.Net.Sockets.TcpListener.Start(Int32 backlog)
   at Winium.Desktop.Driver.Listener.StartListening()

**Comment by nikita1307** [comment]
I am also facing the same issue.. not able to change the port for Winium driver..any leads on this
?

**Comment by iit2013159** [comment]
I have successfully created the multiple instance of Winium.Desktop.Driver and ran in different port. For that you have to use 
public Process getExecutableOnPort(String port) throws IOException{    	
    	return Runtime.getRuntime().exec("C:\\Users\\Winium.Desktop.Driver.exe" +" --port "+port);
    }

after this your exe is up on port defined by you and then you have to just connect to the localhost to the application by
DesktopOptions option = new DesktopOptions();
option.setApplicationPath(locatinOfInspect);
WiniumDriver driver = new WiniumDriver(new URL("http://localhost:9998"), option);
