### ISSUE TITLE
Automating ClickOnce Applications

### ISSUE THREAD

**Issue by Bala810R** [2gis/Winium.Desktop#177]
We have a ClickOne application URL that starts with "http://blahblah/blah.Services/clickonce/BLAH.UI" and we use ruby as binding language.  How should we set desired capabilities for such application under test.

When setting as,
caps['app'] = "http://blahblah/blah.Services/clickonce/BLAH.UI"
@driver = Selenium::WebDriver.for :remote, url: 'http://localhost:9999, desired_capabilities: caps

Received error as 
Selenium::WebDriver::Error::UnknownError: The given path's format is not supported.

Any help will be much appreciated

**Comment by heilwood** [comment]
Is not supported by now, you should modify winium code. I can help you, write me on email heilwood@inbox.lv

**Comment by Bala810R** [comment]
@heilwood Thank you for the response and offer to help.  As a workaround, we managed copy .appref-ms file that gets stored every time we hit ClickOnce application URL from "C:\users\userid\AppData\Roaming\applicationname.appref-ms".  We stored the copied file into our test respository and we are able to launch using .appref-ms

**Comment by ghost** [comment]
you should share the steps so that others facing this issue might get benefited.
