### ISSUE TITLE
Unable to select checkbox

### ISSUE THREAD

**Issue by krishnakanth19** [2gis/Winium.Desktop#179]
Hi,
I'm unable to select the check box in the following image.
When I try to click on that check box, it is clicking out side the check box.
The following is the code I used.

`List<WebElement> ele = driver.findElements(By.id("cbxOpen"));
ele.get(0).click();`

`List<WebElement> ele = driver.findElements(By.className("CheckBox"));
ele.get(0).click();`
It is not working in both ways.

And also it is difficult to get the attributes of the elements like in Selenium. I'm just able to get the "Name" and "ClassName" of the elements.
Is there any methods to read the element attributes.

![checkbox](https://user-images.githubusercontent.com/23556113/29612832-d9e1da3c-8820-11e7-98cb-7542ccc362bf.png)

**Comment by heilwood** [comment]
try to use actions class. Then will click to centre of element:

         public void ClickToCenter(By by)
        
        {
            var Actions = new Actions(_driver);
            var elem = _driver.FindElement(by);
            Actions.Click(elem).Build().Perform();
        }
`

**Comment by heilwood** [comment]
about attributes you can get also Control.Type, AutomationId.

**Comment by krishnakanth19** [comment]
No, It is not working. Still clicking at the outside of the check box.

**Comment by krishnakanth19** [comment]
I got the solution for that. And it's working fine.The following is the code for that.
`new Actions(driver).moveToElement(ele.get(0), 0,0) .moveByOffset(3,7) .click() .build() .perform();`

**Comment by crazzytester** [comment]
@krishnakanth19  I  written the below code for selecting a value from dropdown  list and it is just clicking on the dropdown box and not selecting any values. Where I am going wrong.
List<WebElement> source = driver.findElements(By.id("cmbDealSource"));  //id of the Combo Box
Actions act = new Actions(driver);
act.moveToElement(source.get(0),0,0).moveByOffset(3,7) .click() .build() .perform();
![image](https://user-images.githubusercontent.com/19578147/32664534-8a7f3ec4-c657-11e7-8930-bde52b8204dd.png)
