### ISSUE TITLE
When screen resolution changes, scripts are failing.

### ISSUE THREAD

**Issue by krishnakanth19** [2gis/Winium.Desktop#191]
I'm using a 15-inch laptop. And I wrote some automation scripts in that and those scripts are working fine in that screen resolution. But when I connect the second screen, it is a 21-inch screen winium is clicking on other elements. I used id, name and class names to locate the elements. Is there any solution for this.

**Comment by heilwood** [comment]
when you changing resolution then you need to restart pc.

**Comment by krishnakanth19** [comment]
Hi heilwood,
It's working fine. Thanks.

**Comment by adarshgcek** [comment]
After multiple attempts of restart, I am still facing the above issue.

Can someone please help ?
