### ISSUE TITLE
How to move the driver control from taskbar to application

### ISSUE THREAD

**Issue by rijinjohn** [2gis/Winium.Desktop#208]
When I run my .exe file the application will attach to the taskbar, I want to click the application icon in the taskbar then only it will show sign in page, I am able to do that but my driver control is still in the taskbar, it is not switching to the application. Because of that am not able to do any operation on the sign in page. switch to the window using window handles is not passing driver control to the new window,
How can I do that?

**Comment by nithyasai** [comment]
I am also facing the same issue when i tried launching an .exe file, the application launches properly sometimes and sometime it goes to Taskbar, post which i will get an Element not found error.
It will be great if anybody can help us on this?

**Comment by rijinjohn** [comment]
my issue is solved when I run Winium as administrator.

**Comment by ramkumarsivanandan** [comment]
Can you tell us how did you click on Icon in the taskbar
