### ISSUE TITLE
Proper way to verify element presents in tested app.

### ISSUE THREAD

**Issue by Paravoffka** [2gis/Winium.Desktop#214]
Hello,
I want to create test which going to verify element presents. I want to make sure that Personnel layer displayed in the app. 
![image](https://user-images.githubusercontent.com/35976678/35593736-9201d5c8-05c5-11e8-8f04-fece978ab990.png)
When the element is displayed I don't have any problems, but if element doesn't exist (pervious version of the app) - test fails. 
I tried selenium approach like:
driver.findElement(By.xpath("//*[@Name='Personnel']")).isDisplayed());
and 
driver.findElement(By.xpath("//*[@Name='Personnel']")).getSize();
No Luck :( . Script failed. 

Managed to handle the test: 
try
		{
			if (driver.findElement(By.xpath("//*[@Name='Personnel']"))!=null)
			{
				System.out.println("Test PASSED");
			}
			
		}
		catch(NoSuchElementException ex)
		{
			System.out.println("Test FAILeD");
		}
But it's lots of code if I want to verify bunch of elements. Koroche kak koroche? 

Thanks,
Paravoffka.

**Comment by Parahet** [comment]
Try to use this method

bool IsDisplayed(By by)
{
try
{
   if (driver.findElement(by)!=null)
   {
      return true;
   }
}
catch(NoSuchElementException ex)
{
   System.out.println("Test FAILeD");
   return false;
}
}
