### ISSUE TITLE
Unable To Scrolling the Page, also scroll elements details are not shown in UI SPY Tool or any other inspection tool

### ISSUE THREAD

**Issue by swatidave1987** [2gis/Winium.Desktop#224]
Unable To Scrolling the Page, also scroll elements details are not shown in UI SPY Tool or any other inspection tool. Have anyone faced this kind of issue than please share the solution for same.  @skyline-gleb

**Comment by swatidave1987** [comment]
PFA for the the Scroll Down option in required window in desktop based application for which I need to have element details or any other way through which I can perform scroll down. @skyline-gleb

**Comment by swatidave1987** [comment]
[Issue.docx](https://github.com/2gis/Winium.Desktop/files/1879048/Issue.docx)
@skyline-gleb

**Comment by swatidave1987** [comment]
PFA for the the Scroll Down option in required window in
[UI Spy.docx](https://github.com/2gis/Winium.Desktop/files/1879054/UI.Spy.docx)

desktop based application for which I need to have element details or any other way through which I can perform scroll down. Also attaching the UI SPY element details for outer window scrolling option. @skyline-gleb

**Comment by swatidave1987** [comment]
Requesting you please look into the issue reported in 225/224. as I didn't get any response yet.
 @mayson 
@CSharpRU 
@jonstoneman @tkurnosova

**Comment by skyline-gleb** [comment]
Hi, @swatidave1987 
If the element is not shown in UI Spy, then it has bad testability.
The availability of the elements is entirely due to their support of Microsoft UI Automation. Sometimes it can be improve, see https://github.com/2gis/Winium.Cruciatus/wiki/Improve-app-testability-(RU)
