### ISSUE TITLE
Добавить команды для удобной работы со сложными контролами типа DataGrid, ComboBox

### ISSUE THREAD

**Issue by tkurnosova** [2gis/Winium.Desktop#23]

**Comment by NickAb** [comment]
Something like standard elements from [htmlelements](https://github.com/yandex-qatools/htmlelements).

This will help end-user to reduce boilerplate needed to interact with complex controls by abstracting from selenium commands to higher interface, like *get cell from DataGrid at index*, *select option in ComboBox*, *select date from DatePicker*, etc.
