### ISSUE TITLE
Integration of Winium with Jenkins. 

### ISSUE THREAD

**Issue by Paravoffka** [2gis/Winium.Desktop#235]
Hi, 

I'm trying to integrate Winium with Jenkins using ant. 
Is it possible to do? 

Thanks,
Vlad.

**Comment by Paravoffka** [comment]
I've found solution. 
Jenkins works fine with Winium. The only one problem I faced that's conflict of log4j and Ant. Got rid of log4j and everything started working.

**Comment by dkotowicz** [comment]
I have problem with run winium on jenkins server, because this proces runs on background so driver not could be find elements..

**Comment by Paravoffka** [comment]
Not sure what you mean. Make sure that when you start tested app it should be displayed on foreground.

**Comment by dkotowicz** [comment]
I am looking for a solution so that the tests run in the background. I don't know if it's possible

**Comment by Paravoffka** [comment]
I'm pretty sure that's impossible. Just run it overnight when nobody is using computer, or find separate computer.

**Comment by denisbabas** [comment]
I have problem run winium from a jenkins can you please give me any resources or explain how to do it. Thanks
