### ISSUE TITLE
Winium scroll down is not working

### ISSUE THREAD

**Issue by naveenstats** [2gis/Winium.Desktop#238]
[![enter image description here][1]][1][![enter image description here][2]][2]

I am automating windows application using winium tool using java language. I am selecting a respective player. I am able to selecting player. But in my second table contain scroll down option is there, so my first selection player name is that in the scroll down option, so I can't able to scroll down and select that player.

Here my code first check the player in the list, my first player is not in the gui , that i need to scroll down , then only it can able to select that name..

     if(away_total_players.equals(player))
                        {
                        	
                        
                        		
                        	
                        		WebElement line_up1 = driver.findElementByName(player);      
                        		
                        		if(!line_up1.isDisplayed()) {
                        			System.out.println("hello");
                        			WebElement pl=driver.findElementById("lsvHomeTeamHitters2");
                        			
                        		WebElement b1=pl.findElement(By.name("Vertical Scroll Bar"));
                        			Map<String, Object> scrollInfo = new HashMap<String, Object>();
                        			scrollInfo.put("vertical", "smallIncrement");
                        			scrollInfo.put("count", 10);
                        			driver.executeScript("automation: ScrollPattern.Scroll", b1, scrollInfo);
                                 action.moveToElement(line_up1).doubleClick().build().perform();
                                
                                }
                        		
                        		else
                        		{	

                                    WebElement pl=driver.findElementById("lsvHomeTeamHitters2");
                        			
                        			WebElement wb1=pl.findElement(By.id("Vertical ScrollBar"));
                        			Map<String, Object> scrollInfo = new HashMap<String, Object>();
                        			scrollInfo.put("vertical", "smallIncrement");
                        			scrollInfo.put("count", 10);
                        			driver.executeScript("automation: ScrollPattern.Scroll", wb1, scrollInfo);
                        			
                        			
                                    action.moveToElement(line_up1).doubleClick().build().perform();
                                   
                                   
                                   }
                        		}
                                        

console showing

 > hello 
>
  >org.openqa.selenium.NoSuchElementException: Element cannot be
 > found

  [1]: https://i.stack.imgur.com/OOfzC.png
  [2]: https://i.stack.imgur.com/EejxI.png

**Comment by rateebhatt** [comment]
this error has nothing to do with scrolling. this error means some element is not found by the locator that you have chosen
