### ISSUE TITLE
Mouse actions with winium

### ISSUE THREAD

**Issue by parasuramankumarasami** [2gis/Winium.Desktop#26]
Hi,

is it possible to do the mouse action like right click & double click?
while performing the right click.. i am getting below log.

Here  is the python code..
        user = self.driver.find_element_by_name(" Bhargava B  - Available - Video Capable SW Test Eng - Automation, 2700 - India ENG")
        actionChains = ActionChains(self.driver)
        actionChains.context_click(user).perform()

[16:22:17] [Debug] ACCEPTED REQUEST POST /session/AwesomeSession/element HTTP/1.
1
[16:22:17] [Info] COMMAND findElement
{
  "using": "name",
  "sessionId": "AwesomeSession",
  "value": " Bhargava B  - Available - Video Capable SW Test Eng - Automation, 2
700 - India ENG",
  "SESSIONID": "AwesomeSession"
}
[16:22:18] [Debug] RESPONSE:
OK: {"sessionId":"AwesomeSession","status":0,"value":{"ELEMENT":"986660328-5"}}

[16:22:18] [Debug] Client closed

[16:22:18] [Debug] Waiting for a connection...
[16:22:18] [Debug] ACCEPTED REQUEST POST /session/AwesomeSession/moveto HTTP/1.1

[16:22:18] [Info] COMMAND mouseMoveTo
{
  "sessionId": "AwesomeSession",
  "element": "986660328-5",
  "SESSIONID": "AwesomeSession"
}
[16:22:18] [Debug] RESPONSE:
OK: {"sessionId":"AwesomeSession","status":0,"value":null}
[16:22:18] [Debug] Client closed

[16:22:18] [Debug] Waiting for a connection...
[16:22:18] [Debug] ACCEPTED REQUEST POST /session/AwesomeSession/click HTTP/1.1

[16:22:18] [Info] COMMAND mouseClick
{
  "button": 2,
  "sessionId": "AwesomeSession",
  "SESSIONID": "AwesomeSession"
}
[16:22:18] [Debug] RESPONSE:
OK: {"sessionId":"AwesomeSession","status":0,"value":null}
[16:22:18] [Debug] Client closed

[16:22:18] [Debug] Waiting for a connection...

**Comment by skyline-gleb** [comment]
Сode is correct and working on the test application.
Element has the coordinates? (can be found in UISpy)

**Comment by parasuramankumarasami** [comment]
Please find the properties of the element from the UIspy

AutomationElement
  General Accessibility
    AccessKey:	""
    AcceleratorKey:	""
    IsKeyboardFocusable:	"False"
    LabeledBy:	"(null)"
    HelpText:	""

  State
    IsEnabled:	"True"
    HasKeyboardFocus:	"False"

  Identification
    ClassName:	"NetUIVirtualListView"
    ControlType:	"ControlType.Pane"
    Culture:	"(null)"
    AutomationId:	""
    LocalizedControlType:	"Pane"
    Name:	"Search Results"
    ProcessId:	"3152 (lync)"
    RuntimeId:	"42 66424 2 440997424 0"
    IsPassword:	"False"
    IsControlElement:	"True"
    IsContentElement:	"True"

  Visibility
    BoundingRectangle:	"(1190, 302, 476, 423)"
    ClickablePoint:	"(null)"
    IsOffscreen:	"False"

ControlPatterns
  Scroll
    HorizontalScrollPercent:	"-1"
    HorizontalViewSize:	"100"
    VerticalScrollPercent:	"-1"
    VerticalViewSize:	"100"
    HorizontallyScrollable:	"False"
    VerticallyScrollable:	"False"

  ScrollItem

**Comment by skyline-gleb** [comment]
this code
```python
user = self.driver.find_element_by_class_name("NetUIListViewItem")
actionChains = ActionChains(self.driver)
actionChains.context_click(user).perform()
```
worked with my Lync and opens context menu. I don't know what to tell..

**Comment by parasuramankumarasami** [comment]
ok.. can you please send me code to right click & click copy...

thanks.

On Tue, Jul 14, 2015 at 5:28 PM, Gleb Golovin <notifications@github.com>
wrote:

> this code
>
> user = self.driver.find_element_by_class_name("NetUIListViewItem")
> actionChains = ActionChains(self.driver)
> actionChains.context_click(user).perform()
>
> worked with my Lync and opens context menu. I don't know what to tell..
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/2gis/Winium.Desktop/issues/26#issuecomment-121215417>.
>



-- 

*Parasuram**09886867999*
*Excited to be Alive.*
*12 Legs to the FUNCTIONS!!!.*
*GO-GETTER Ragu & Valar's Diamond leg!*
*Expecting Miracles to Happen!*
*"Some People find Opportunity in every Challenges, while some people find
Challenges in every Opportunity"- Hawkins*

**Comment by skyline-gleb** [comment]
right click & click copy
```python
item = driver.find_element_by_class_name('NetUIListViewItem')

actionChains = ActionChains(driver)
actionChains.context_click(item).perform()

menu = driver.find_element_by_class_name('NetUIToolWindow')
menu.find_element_by_name('Копировать').click()
```

**Comment by parasuramankumarasami** [comment]
Hi Gleb,

I tried in my Lync... it didnt do a right click...

On Tue, Jul 14, 2015 at 5:28 PM, Gleb Golovin <notifications@github.com>
wrote:

> this code
>
> user = self.driver.find_element_by_class_name("NetUIListViewItem")
> actionChains = ActionChains(self.driver)
> actionChains.context_click(user).perform()
>
> worked with my Lync and opens context menu. I don't know what to tell..
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/2gis/Winium.Desktop/issues/26#issuecomment-121215417>.
>



-- 

*Parasuram**09886867999*
*Excited to be Alive.*
*12 Legs to the FUNCTIONS!!!.*
*GO-GETTER Ragu & Valar's Diamond leg!*
*Expecting Miracles to Happen!*
*"Some People find Opportunity in every Challenges, while some people find
Challenges in every Opportunity"- Hawkins*

**Comment by parasuramankumarasami** [comment]
Is it possible, you to try it Windows 7?

On Thu, Jul 16, 2015 at 3:09 PM, Parasuraman CAM <
parasuramankumarasami@gmail.com> wrote:

> Hi Gleb,
>
> I tried in my Lync... it didnt do a right click...
>
> On Tue, Jul 14, 2015 at 5:28 PM, Gleb Golovin <notifications@github.com>
> wrote:
>
>> this code
>>
>> user = self.driver.find_element_by_class_name("NetUIListViewItem")
>> actionChains = ActionChains(self.driver)
>> actionChains.context_click(user).perform()
>>
>> worked with my Lync and opens context menu. I don't know what to tell..
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/2gis/Winium.Desktop/issues/26#issuecomment-121215417>
>> .
>>
>
>
>
> --
>
> *Parasuram**09886867999 <09886867999>*
> *Excited to be Alive.*
> *12 Legs to the FUNCTIONS!!!.*
> *GO-GETTER Ragu & Valar's Diamond leg!*
> *Expecting Miracles to Happen!*
> *"Some People find Opportunity in every Challenges, while some people find
> Challenges in every Opportunity"- Hawkins*
>



-- 

*Parasuram**09886867999*
*Excited to be Alive.*
*12 Legs to the FUNCTIONS!!!.*
*GO-GETTER Ragu & Valar's Diamond leg!*
*Expecting Miracles to Happen!*
*"Some People find Opportunity in every Challenges, while some people find
Challenges in every Opportunity"- Hawkins*

**Comment by skyline-gleb** [comment]
Development was under Windows 7, earlier. There is no problem.
When you start automate, Lync window visible? Or in background?

**Comment by parasuramankumarasami** [comment]
i have started automating Lync... Lync in visible mode...

On Fri, Jul 17, 2015 at 8:43 AM, Gleb Golovin <notifications@github.com>
wrote:

> Development was under Windows 7, earlier. There is no problem.
> When you start automate, Lync window visible? Or in background?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/2gis/Winium.Desktop/issues/26#issuecomment-122157494>.
>



-- 

*Parasuram**09886867999*
*Excited to be Alive.*
*12 Legs to the FUNCTIONS!!!.*
*GO-GETTER Ragu & Valar's Diamond leg!*
*Expecting Miracles to Happen!*
*"Some People find Opportunity in every Challenges, while some people find
Challenges in every Opportunity"- Hawkins*

**Comment by parasuramankumarasami** [comment]
it works in windows 7 as well with python selenium version 2.46 & python version 34.

**Comment by skyline-gleb** [comment]
But don't work with ...?

**Comment by parasuramankumarasami** [comment]
python Selenium 2.46.1

On Thu, Jul 30, 2015 at 3:49 PM, Gleb Golovin <notifications@github.com>
wrote:

> But don't work with ...?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/2gis/Winium.Desktop/issues/26#issuecomment-126262153>.
>



-- 

*Parasuram**09886867999*
*Excited to be Alive.*
*12 Legs to the FUNCTIONS!!!.*
*GO-GETTER Ragu & Valar's Diamond leg!*
*Expecting Miracles to Happen!*
*"Some People find Opportunity in every Challenges, while some people find
Challenges in every Opportunity"- Hawkins*

**Comment by skyline-gleb** [comment]
I am very surprised that this may be related. Now all the work?

**Comment by parasuramankumarasami** [comment]
Yes.. it works fine. thanks.

On Thu, Jul 30, 2015 at 4:02 PM, Gleb Golovin <notifications@github.com>
wrote:

> I am very surprised that this may be related. Now all the work?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/2gis/Winium.Desktop/issues/26#issuecomment-126268648>.
>



-- 

*Parasuram**09886867999*
*Excited to be Alive.*
*12 Legs to the FUNCTIONS!!!.*
*GO-GETTER Ragu & Valar's Diamond leg!*
*Expecting Miracles to Happen!*
*"Some People find Opportunity in every Challenges, while some people find
Challenges in every Opportunity"- Hawkins*
