### ISSUE TITLE
How can I click on the particular node of treeview using Winium and Java

### ISSUE THREAD

**Issue by truptibhatt** [2gis/Winium.Desktop#272]
![issue1](https://user-images.githubusercontent.com/21361614/46592887-5c053700-cae4-11e8-92b1-0b9c85fd97b6.jpg)

i have tried following code: But no luck. @skyline-gleb  do we have support for it?

First Apporach
By locator1=By.xpath("//*[@ControlType='ControlType.TreeItem' and @name='Account']");
driver.findElement(locator1).click();
second Approach
By locator1=By.xpath("//*[@Automationid='tvObjects' and @name='Account']");
driver.findElement(locator1).click();

**Comment by truptibhatt** [comment]
@Sourabh25 or @SharonJacob - can you  help here?

**Comment by heilwood** [comment]
@truptibhatt  XPath is slow, better to find child element in parent. driver.findElement(By.id("tvObjects")).findElement(By.name("Account"));

**Comment by truptibhatt** [comment]
Hi Can you send me the code

**Comment by truptibhatt** [comment]
@heilwood - No luck. it is throwing an error like ": [INFO] Element 'Name: Account' not found"

**Comment by SharonJacob** [comment]
Hi @truptibhatt if the issue still persists, we can do a screen share. shoot me an email at disha.sharon@gmail.com

**Comment by heilwood** [comment]
@truptibhatt its hard to investigate like that, @SharonJacob suggested you to share screen, this is the better way, if you will not solve this issues, then i will try to help you )

**Comment by truptibhatt** [comment]
Thanks a lot @SharonJacob  and @heilwood  for such a wonderful support. Finally i am able to click on treenode.

**Comment by truptibhatt** [comment]
@SharonJacob  and @heilwood - one more question, i wanted to double click on tree node and i tried following code: any better solution for it? Can you please confirm?

```
 driver.findElement(By.id("tvObjects")).findElement(By.name("Account Billing Summary")).click();
		 Robot robot = new Robot();
		
	        robot.delay(1500);        // delay is to make code wait for mentioned milliseconds before executing next step	
	        robot.mousePress(InputEvent.BUTTON1_DOWN_MASK); // press left click	
	        robot.mouseRelease(InputEvent.BUTTON1_DOWN_MASK); // release left click	
	        robot.mousePress(InputEvent.BUTTON1_DOWN_MASK); // press left click	
	        robot.mouseRelease(InputEvent.BUTTON1_DOWN_MASK); // 
```

**Comment by SharonJacob** [comment]
@truptibhatt I think Actions is a better approach. I've sent a code snippet as a response to your email.
Let me know if you have any questions

**Comment by truptibhatt** [comment]
@SharonJacob -Thanks.

 I have one table and i want to click on checkbox of particular row.

Goal: I want to click on the checkbox of a row whose name is " Row 2" (contains Row 2) and having helptext contains DataGridViewCheckBoxCell

Code: 
First Approach: In Row 0 there is a space before name. Checkbox is having name and need to add one more property helptext to uniquely identify it.But it is always picking first row even if i pass " Row 1"	
```
WebElement player22 = driver.findElement(By.name(" Row 0")).findElement(By.xpath("//*[contains(@HelpText,'DataGridViewCheckBoxCell')]"));  
		
Actions act= new Actions(driver);
act.sesndKeys(player22,Keys.SPACE).build().perform();
```
Second Approach: It is throwing an error. 
```
By locator=By.xpath("//*[(@Name,'Row 3')] and [contains(@HelpText,'DataGridViewCheckBoxCell')]"); 
WebElement player = driver.findElement( locator  ); 
Actions act= new Actions(driver);
act.sesndKeys( player  ,Keys.SPACE).build().perform();

```
![image](https://user-images.githubusercontent.com/21361614/46994937-1b389e00-d134-11e8-87ac-8fc8fa30f343.png)

**Comment by truptibhatt** [comment]
@SharonJacob or @heilwood - can you look into above issue?

**Comment by truptibhatt** [comment]
@SharonJacob  or @heilwood  - can you check above issue if you have quick solution?

**Comment by truptibhatt** [comment]
@SharonJacob  and @heilwood - i tried it multiple solution and finally it is working now . thanks

**Comment by ajit2548** [comment]
@truptibhatt can you please share the solution here?

**Comment by ghost** [comment]
@truptibhatt @SharonJacob Hi - I'm having the same issue but with only Windows 10 - would you be able to help or post the solution? Many thanks!

**Comment by mrjaiswar** [comment]
@truptibhatt  @SharonJacob Hi, I am stuck with the same problem. It's an legacy system build 24+ years. Please refer the screenshots - I want to access the child table nodes mentioned under the parent 'table'. Please help. Thanks!!
![tempsnip](https://user-images.githubusercontent.com/11874038/76487616-d11e2e00-6487-11ea-82a5-21f87cab1ac0.png)

**Comment by sandeep91anand** [comment]
Hi @SharonJacob Need to click/expand the tree items(tree view) on my project so that I can do action on particular node .
Please suggest any solution for the it. 
![2021-06-11_18h58_41](https://user-images.githubusercontent.com/85747876/121698178-6248de00-caeb-11eb-9858-ef01382dd672.png)
![2021-06-11_19h24_47](https://user-images.githubusercontent.com/85747876/121698246-6ffe6380-caeb-11eb-810b-eb4aca3c8092.png)
