### ISSUE TITLE
Desktop App with Chrome Legacy Window

### ISSUE THREAD

**Issue by williamborba** [2gis/Winium.Desktop#279]
Hello, any tips for this problem?

I need to test a windows application with **Chrome Legacy Window** embeded. The application **inspect.exe ** does not find the elements for **click** ...

I'm also trying to use this command `https://github.com/2gis/Winium.Desktop/wiki/Supported-Commands#mousemoveto` but the mouse always misses the target ...

Has anyone gone through this, or do you have any ideas?

code
```python
from selenium import webdriver
from selenium.webdriver.common.keys import Keys

driver = webdriver.Remote (
            command_executor = 'http: // localhost: 9999',
            desired_capabilities = {
                'launchDelay': '5',
                'keyboardSimulator': 'BasedOnInputSimulatorLib',
                'debugConnectToRunningApp': 'true',
                'app': r'C: \\ Program Files (x86) \\ Tasker Client SIN \\ Tasker Client.exe '
            })

browser = driver.find_element_by_id ('TChromiumBrowser')

driver_chrome_options = webdriver.ChromeOptions ()
driver_chrome_options.add_argument ('headless')

driver_chrome = webdriver.Chrome (
        executable_path = "chromedriver.exe",
        chrome_options = driver_chrome_options)

# how to switch context into Desktop and Chrome?
```

**Comment by rochakbhalla** [comment]
> Hello, any tips for this problem?
> 
> I need to test a windows application with **Chrome Legacy Window** embeded. The application **inspect.exe ** does not find the elements for **click** ...
> 
> I'm also trying to use this command `https://github.com/2gis/Winium.Desktop/wiki/Supported-Commands#mousemoveto` but the mouse always misses the target ...
> 
> Has anyone gone through this, or do you have any ideas?
> 
> code
> 
> ```python
> from selenium import webdriver
> from selenium.webdriver.common.keys import Keys
> 
> driver = webdriver.Remote (
>             command_executor = 'http: // localhost: 9999',
>             desired_capabilities = {
>                 'launchDelay': '5',
>                 'keyboardSimulator': 'BasedOnInputSimulatorLib',
>                 'debugConnectToRunningApp': 'true',
>                 'app': r'C: \\ Program Files (x86) \\ Tasker Client SIN \\ Tasker Client.exe '
>             })
> 
> browser = driver.find_element_by_id ('TChromiumBrowser')
> 
> driver_chrome_options = webdriver.ChromeOptions ()
> driver_chrome_options.add_argument ('headless')
> 
> driver_chrome = webdriver.Chrome (
>         executable_path = "chromedriver.exe",
>         chrome_options = driver_chrome_options)
> 
> # how to switch context into Desktop and Chrome?
> ```

**Comment by rochakbhalla** [comment]
Is there anybody who can help us on this because I am also facing the similar issue with one of my application which is actually .exe but internally opens a Chrome Legacy Window.
Is there option to interact with that..??
