### ISSUE TITLE
Python 3.4.3

### ISSUE THREAD

**Issue by parasuramankumarasami** [2gis/Winium.Desktop#28]
Hi,

When run my test with the python version 27 it work fine without any issue in windows 8.1.
if i run the test with python version 34. i am getting error. i was not able to find any element with name or id or class name.

[17:06:18] [Debug] ACCEPTED REQUEST POST /session/AwesomeSession/elements HTTP/1.1 
[17:06:18] [Info] COMMAND findElements
{
  "sessionId": "AwesomeSession",
  "using": "css selector",
  "value": ".NetUITextbox",
  "SESSIONID": "AwesomeSession"
} 
[17:06:18] [Debug] RESPONSE:
NotImplemented: {"sessionId":"AwesomeSession","status":9,"value":"'css selector' is not valid or implemented searching strategy."} 
[17:06:18] [Debug] Client closed
 
[17:06:18] [Debug] Waiting for a connection... 

what i need to do work with python 34?

**Comment by alandreev** [comment]
Hello,

I've got the same issue when first tried with Python 3.4.3. Thus sent an e-mail to Gleb, so awaiting any answers here or by e-mail.
And I''m even getting the same things with 2.10 as well.

Thanks,

**Comment by NickAb** [comment]
Could you please provide code sample that you are using to find elements? Based on stacktrace, it seems that `find_element_by_css_selector` is used, which, I believe, is not a supported strategy for Windows desktop platform. Here is a list of supported strategies: `id`, `name`, `class name`.

**Comment by alandreev** [comment]
As for me, I used the example provided on https://github.com/2gis/Winium.Desktop/wiki/Magic-Samples (the first one) related to calc.exe where the find element is used as:
window = driver.find_element_by_class_name('CalcFrame')
And I am gettin the same error

**Comment by parasuramankumarasami** [comment]
HI,

I am using find_element_by_name for the Lync application.
self.win = self.driver.find_element_by_name("Lync Basic")

On Tue, Jul 28, 2015 at 7:44 PM, alandreev <notifications@github.com> wrote:

> As for me, I used the example provided on
> https://github.com/2gis/Winium.Desktop/wiki/Magic-Samples (the first one)
> related to calc.exe where the find element is used as:
> window = driver.find_element_by_class_name('CalcFrame')
> And I am gettin the same error
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/2gis/Winium.Desktop/issues/28#issuecomment-125623454>.
>



-- 

*Parasuram**09886867999*
*Excited to be Alive.*
*12 Legs to the FUNCTIONS!!!.*
*GO-GETTER Ragu & Valar's Diamond leg!*
*Expecting Miracles to Happen!*
*"Some People find Opportunity in every Challenges, while some people find
Challenges in every Opportunity"- Hawkins*

**Comment by skyline-gleb** [comment]
Hi!
Which Selenium-binding version you're using?

**Comment by skyline-gleb** [comment]
Problem in python selenium binding 2.46.1 version. Downgrade to 2.46, please :)
p.s. last binding [source code](https://github.com/SeleniumHQ/selenium/blob/61e866d43e6c149bba363d63d544c15d3ed0a72e/py/selenium/webdriver/remote/webdriver.py#L693) right, but 2.46.1 with bug

**Comment by parasuramankumarasami** [comment]
yes.. i am using selenium version 2.46.1.. how i can downgrade to 2.46..

**Comment by skyline-gleb** [comment]
Using [Requirements Files](https://pip.pypa.io/en/latest/user_guide.html#requirements-files).
- create *requirements.txt* file in project folder;
- add line "selenium==2.46".
and PyCharm installed this version (for [help](https://www.jetbrains.com/pycharm/help/creating-requirement-files.html)).

**Comment by parasuramankumarasami** [comment]
Thanks.. its works fine with the Selenium 2.46 version

**Comment by alandreev** [comment]
Yep, it works fine for me as well with the provided configuration!
Thanks a lot!

**Comment by rohantambe** [comment]
> 

hi sir , im not using PyCharm, would you be able to tell me how to do this in Spyder IDE. it would be really helpful
