### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Bibigon1976** [2gis/Winium.Desktop#29]
Hello, i am getting this error:
 
File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode 
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)

every time with this code:

from selenium import webdriver
driver = webdriver.Remote(
    command_executor='http://localhost:9999',
    desired_capabilities={
        "debugConnectToRunningApp": 'false',
        "app": r"C:/windows/system32/calc.exe"
    })
win = driver.find_element_by_class_name('CalcFrame')
driver.close()

Any suggestion? Thanks.

**Comment by skyline-gleb** [comment]
It is right code.
Which Selenium-binding version are you using?

**Comment by Bibigon1976** [comment]
Selenium 2.46.1
Python 3.4.3

**Comment by skyline-gleb** [comment]
Please, downgrade to 2.46 version. 2.46.1 with bug (see https://github.com/2gis/Winium.Desktop/issues/28).
This may be a problem.

**Comment by Bibigon1976** [comment]
Yes, that helped, thanks a lot.
