### ISSUE TITLE
Right Click & Double Click

### ISSUE THREAD

**Issue by parasuramankumarasami** [2gis/Winium.Desktop#31]
Hi,
@nwlunatic 
@shiron @NickAb
@alandreev
@skyline-gleb
I am using below 
OS: windows 8.1.
Python:34
Selenium: 2.46

Right click & double click is not working...

**Comment by skyline-gleb** [comment]
You can record video? And i too.
p.s. source code, run and executing

**Comment by skyline-gleb** [comment]
Hi,
you have this problem now?

**Comment by parasuramankumarasami** [comment]
No.. u can close.
