### ISSUE TITLE
Run application with parameters.

### ISSUE THREAD

**Issue by Bibigon1976** [2gis/Winium.Desktop#33]
Hello, if it possible to start application with parameters, like for instance notepad.exe /P

This code execution causes exception "Path does not exist.":

driver = webdriver.Remote(
    command_executor='http://localhost:9999',
    desired_capabilities={
        "debugConnectToRunningApp": 'false',
        "app": r"C:/windows/system32/notepad.exe /P"
    })

**Comment by skyline-gleb** [comment]
Hi!
Thanks, we implement this functional.
