### ISSUE TITLE
Add search pattern to the FindElements

### ISSUE THREAD

**Issue by Bibigon1976** [2gis/Winium.Desktop#43]
It would be nice to search elements by using search patterns like this: driver.find_elements_by_id('Element_1_*')

and for example with this list:
Element_1_1
Element_1_2
Element_1_3
Element_2_1
Element_2_2

it will return [Element_1_1,Element_1_2,Element_1_3]

Thanks.

**Comment by ksuzu** [comment]
да, мне бы тоже пригодилось

**Comment by skyline-gleb** [comment]
@Bibigon1976 example for you `find_elements_by_xpath('*[starts-with(@Name, 'Element_')]'`

**Comment by skyline-gleb** [comment]
@ksuzu use xpath expression as you need to
