### ISSUE TITLE
v1.3.0 build It contains only the exe file

### ISSUE THREAD

**Issue by prodigy007** [2gis/Winium.Desktop#47]
Hello!
https://yadi.sk/i/c-F3NLW6inmiv
I tried to throw the file in the last assembly, but the launch is still hanging indefinitely.

and You can write an example for all of the items in C # desirable:
>>>
Add extended driver commands (see Winium.Elements for bindings). Extended commands simplify usage of following elements:
--ComboBox (collapse, expand, is expanded, find selected item, scroll to item)
--DataGrid (row count, column count, find cell, scroll to cell, select cell)
--ListBox (scroll to item)
---Menu (find item, select item)

**Comment by skyline-gleb** [comment]
Приветствую! Кажется мы можем продолжить общение на русском.
Если я правильно понял, смущает то что драйвер после запуска продолжает работать и висит консольное приложение? Это верная его работа, ведь драйвер, это "сервер", который слушает на определенном порту команды.
А насчет примеров - на [странице проекта](https://github.com/2gis/Winium.Elements) описано как начать использовать и пример работы с элементом DataGrid. С остальными аналогично. Но если будут конкретные вопросы, задавайте)

**Comment by prodigy007** [comment]
думал на русском нельзя.

Точно работает, я думал оно подвисло.
В любом случае в итоговом билде последнем должны быть другие dll ? для тех кто 1-й раз скачивает проект, в 1.2 получается, они не просто так были.

Все спасибо за пример, не увидел  сам. Вопросов больше нет.

**Comment by skyline-gleb** [comment]
Спасибо за отзыв)
Все dll "влиты" в один exe-файл. Так кажется удобней распространять и использовать.
Если интересна реализация, то она почти [в одну строку](https://github.com/2gis/Winium.Desktop/blob/master/src/Winium.Desktop.Driver/Winium.Desktop.Driver.csproj#L159) с использованием [ILMerge](https://www.nuget.org/packages/ilmerge).
