### ISSUE TITLE
can I use send_keys

### ISSUE THREAD

**Issue by sanjeets** [2gis/Winium.Desktop#55]
I keep getting exceptions when I try using send_keys on a an edit field.
Sanjeet

**Comment by skyline-gleb** [comment]
Hi,
could you give the executable code?

**Comment by NickAb** [comment]
Could you provide a stack trace of exception and driver log? Driver log can be copied form driver window if it was started with `--verbose` option, or can be read from file if it was started with `--log-path=FILE` option.

**Comment by sanjeets** [comment]
![error_location](https://cloud.githubusercontent.com/assets/4698614/10378204/d131a660-6dc4-11e5-8efd-c72d2352fd45.PNG)

Error when trying to get location on an element

**Comment by sanjeets** [comment]
Here is my code:
       elem = window.find_elements_by_id("1008")
        elem[0].click()
        elem[1].click()
click is causing an exception see below for exception

**Comment by sanjeets** [comment]
![debugerror](https://cloud.githubusercontent.com/assets/4698614/10380215/d28203e2-6dcf-11e5-9a79-d0591b82bcf3.PNG)

**Comment by skyline-gleb** [comment]
repeat with driver as administrator, please. Your OS is answered "Access is denied"
