### ISSUE TITLE
Feature: Disable start of application

### ISSUE THREAD

**Issue by Yserz** [2gis/Winium.Desktop#66]
Hey,

I'm looking for an option to disable the start of an application through the winium desktop driver.
I'm testing a electron application where I don't have to start the application through winium since I have to start the application through chromedriver to pass several command line options. For now I just added the calculator as the app under test but this is not a nice solution. It would be cool to just omit the app path parameter in the capabilities for winium.

**Comment by zebraxxl** [comment]
You can set "debugConnectToRunningApp" to true in desired capabilities. This will skip application starting.

**Comment by NickAb** [comment]
You can find list of supported desired capabilities with description [here] (https://github.com/2gis/Winium.Desktop/wiki/Capabilities)

**Comment by Yserz** [comment]
Works like a charm. Thx for the pointer :)
