### ISSUE TITLE
Using XPath

### ISSUE THREAD

**Issue by marat-akm** [2gis/Winium.Desktop#77]
Good day!
When I try to use the XPath raises many questions.
What should be used as a node?
Which operators and how do I apply?

Please supplement the Wiki section more information about the use of XPath.

**Comment by skyline-gleb** [comment]
@marat-akm good offer, thanks! :+1:

**Comment by skyline-gleb** [comment]
Added link on more examples [wiki/Finding-Elements#xpath](https://github.com/2gis/Winium.Desktop/wiki/Finding-Elements#xpath)

**Comment by raulthandani** [comment]
Please provide example for xpath to acess child, direct child, foward , backward object.
