### ISSUE TITLE
How to configure With Protractor

### ISSUE THREAD

**Issue by anujmahi** [2gis/Winium.Desktop#80]
Hi 

How can we configure winium with protractor. What changes do we need to make in config file to work with winium.Desktop.

please help.

Thanks

**Comment by skyline-gleb** [comment]
@anujmahi Hi! Sorry to take so long. But we have no such experience

**Comment by anujmahi** [comment]
@skyline-gleb
Hi thanks for replying. We have found the solution on how to configure it with protractor.

**Comment by skyline-gleb** [comment]
It's great! If you could tell us about the solution, it could be useful to others. I can add it to the Wiki :book:

**Comment by ESrini** [comment]
Hi
I have an add-in for Office applications, which is based on Angular JS. I need to automate this Angular JS based desktop application.  Can someone help me out to handle protractor with winium ?

**Comment by anujmahi** [comment]
@ESrini 
You have to write your own api reference in JS to use winimun along with protractor.

**Comment by anujmahi** [comment]
@skyline-gleb 
I would love to post the solution. Can you tell me his to do that.

**Comment by ESrini** [comment]
@anujmahi Thanks for your response. I am new to protractor and winium. It would be helpful if you post the solution in detail may be if possible with some example. Thanks in advance ! Awaiting your response.

**Comment by ESrini** [comment]
@anujmahi @skyline-gleb Your response is much appreciated please. Thanks!

**Comment by AdityaAutomationTechniques** [comment]
> @skyline-gleb
> Hi thanks for replying. We have found the solution on how to configure it with protractor.

Can you give a link or post it here or email the portion of code( related conf.js and spec.js files and other files) to meaditya03@gmail.com ???

**Comment by ghost** [comment]
@anujmahi Can you post the solution to my email ID - meaditya03@gmail.com

**Comment by AyeshaBegam** [comment]
Hi even I want to run Command prompt through java script which is for Angular project using winnium. can some1 help with the code??
