### ISSUE TITLE
Winium.Desktop driver doesn't click on elements inside a Parallels/VmWare Windows VM

### ISSUE THREAD

**Issue by hideintheclouds** [2gis/Winium.Desktop#84]
The click operation doesn't seem to be working inside a Parallels Windows VM Machine

I have a VM with Windows 7 installed on my Mac.
I have started the Winium.Desktop.Driver.exe and tried to run some simple steps on several applications, but click doesn't seem to be working correctly. 

I have tried the Magic sample with calc.exe (https://github.com/2gis/Winium.Desktop/wiki/Magic-Samples).
It seems that the driver opens the application, but after that, it cannot click on elements from the window.

I have used Inspect and UIAVerify to analyse the properties of the View menu form the calculator, and the results are:

BoundingRectangle:	1340,157,65,38
OR
BoundingRectangle:	{l:1340 t:157 r:1405 b:195}

Am I missing something? Do I need to activate the element before clicking on it?

According to the winium.log, it seems that the driver is trying to click correctly on the pair of coordinates of the View menu (1372,175):

09:47:48 [INFO] Click on 'type: ControlType.MenuItem, uid: Item 1, name: View' element at (1372, 175) ClickablePoint

I have ran Winium.Desktop.Driver.exe with --verbose and --log-path parameters, and this is what is displayed:
```
09:47:47 [DEBUG] ACCEPTED REQUEST POST /session HTTP/1.1
09:47:47 [INFO] COMMAND newSession
{
  "desiredCapabilities": {
    "app": "C:/windows/system32/calc.exe",
    "debugConnectToRunningApp": "false"
  }
}
09:47:47 [DEBUG] Current keyboard simulator: BasedOnInputSimulatorLib
09:47:47 [DEBUG] RESPONSE:
OK: {"sessionId":"AwesomeSession","status":0,"value":{"app":"C:/windows/system32/calc.exe","args":"","debugConnectToRunningApp":false,"innerPort":9998,"keyboardSimulator":1,"launchDelay":0}}
09:47:47 [DEBUG] Client closed

09:47:47 [DEBUG] Waiting for a connection...
09:47:47 [DEBUG] ACCEPTED REQUEST POST /session/AwesomeSession/element HTTP/1.1
09:47:47 [INFO] COMMAND findElement
{
  "using": "class name",
  "sessionId": "AwesomeSession",
  "value": "CalcFrame",
  "SESSIONID": "AwesomeSession"
}
09:47:48 [DEBUG] RESPONSE:
OK: {"sessionId":"AwesomeSession","status":0,"value":{"ELEMENT":"459502-7"}}
09:47:48 [DEBUG] Client closed

09:47:48 [DEBUG] Waiting for a connection...
09:47:48 [DEBUG] ACCEPTED REQUEST POST /session/AwesomeSession/element/459502-7/element HTTP/1.1
09:47:48 [INFO] COMMAND findChildElement
{
  "using": "id",
  "sessionId": "AwesomeSession",
  "id": "459502-7",
  "value": "MenuBar",
  "SESSIONID": "AwesomeSession",
  "ID": "459502-7"
}
09:47:48 [DEBUG] RESPONSE:
OK: {"sessionId":"AwesomeSession","status":0,"value":{"ELEMENT":"4065077-8"}}
09:47:48 [DEBUG] Client closed

09:47:48 [DEBUG] Waiting for a connection...
09:47:48 [DEBUG] ACCEPTED REQUEST POST /session/AwesomeSession/element/4065077-8/element HTTP/1.1
09:47:48 [INFO] COMMAND findChildElement
{
  "using": "name",
  "sessionId": "AwesomeSession",
  "id": "4065077-8",
  "value": "View",
  "SESSIONID": "AwesomeSession",
  "ID": "4065077-8"
}
09:47:48 [DEBUG] RESPONSE:
OK: {"sessionId":"AwesomeSession","status":0,"value":{"ELEMENT":"8130154-9"}}
09:47:48 [DEBUG] Client closed

09:47:48 [DEBUG] Waiting for a connection...
09:47:48 [DEBUG] ACCEPTED REQUEST POST /session/AwesomeSession/element/8130154-9/click HTTP/1.1
09:47:48 [INFO] COMMAND clickElement
{
  "sessionId": "AwesomeSession",
  "id": "8130154-9",
  "SESSIONID": "AwesomeSession",
  "ID": "8130154-9"
}
09:47:48 [INFO] Click on 'type: ControlType.MenuItem, uid: Item 1, name: View' element at (1372, 175) ClickablePoint
09:47:48 [DEBUG] RESPONSE:
OK: {"sessionId":"AwesomeSession","status":0,"value":null}
09:47:48 [DEBUG] Client closed

09:47:48 [DEBUG] Waiting for a connection...
09:47:48 [DEBUG] ACCEPTED REQUEST POST /session/AwesomeSession/element/8130154-9/element HTTP/1.1
09:47:48 [INFO] COMMAND findChildElement
{
  "using": "name",
  "sessionId": "AwesomeSession",
  "id": "8130154-9",
  "value": "Scientific",
  "SESSIONID": "AwesomeSession",
  "ID": "8130154-9"
}
09:47:58 [INFO] Element 'Name: Scientific' not found
09:47:58 [DEBUG] RESPONSE:
OK: {"sessionId":"AwesomeSession","status":7,"value":{"error":"no such element","stacktrace":"   at Winium.Desktop.Driver.CommandExecutors.FindChildElementExecutor.DoImpl()\r\n   at Winium.Desktop.Driver.CommandExecutors.CommandExecutorBase.Do()","message":"Element cannot be found"}}
09:47:58 [DEBUG] Client closed

09:47:58 [DEBUG] Waiting for a connection...
```

**Comment by NickAb** [comment]
This might be related to the problem of clicking into wrong location when non default (100%) screen scale is setup in `Appearance and Personalization -> Adjust screen resolution`.

Can you please describe your setup, like what resolution do you have, are you using retina screen, screen scaling or anything related?

**Comment by hideintheclouds** [comment]
Thank you for your quick reply Nick,

That was the problem indeed. In both Parallels and VmWare the default value in the virtual machine was something greater than 100% screen scale.
Changing it to 100% seems to fix the issues. The driver clicks inside the app and I am able to successfully run the Calc example.

**Comment by NickAb** [comment]
I have opened general issue for miss-clicking related to screen scale https://github.com/2gis/Winium.Desktop/issues/85

**Comment by Asha1213** [comment]
Not able to click an element in my application. I can click in other application like notepad, calc
