### ISSUE TITLE
Winium should always return string when getting bool/int attributes

### ISSUE THREAD

**Issue by sobolewska** [2gis/Winium.Desktop#93]
When, in python, getting attributes like IsOffscreenProperty, IsEnabled, or NativeWindowHandle, returned value is not a string, thus the selenium get_attribute is giving error that .lower() is not available for type

    def get_attribute(self, name):
        resp = self._execute(Command.GET_ELEMENT_ATTRIBUTE, {'name': name})
        attributeValue = ''
        if resp['value'] is None:
            attributeValue = None
        else:
            attributeValue = resp['value']
            if name != 'value' and attributeValue.lower() in ('true', 'false'):
                attributeValue = attributeValue.lower()
        return attributeValue

**Comment by sobolewska** [comment]
in the meantime, as a workaround, I can call `_execute` directly

    from selenium.webdriver.remote.command import Command
    element._execute(Command.GET_ELEMENT_ATTRIBUTE, {'name': "IsOffscreen"})

**Comment by skyline-gleb** [comment]
@sobolewska sorry, we fixed this, but not released so far. New version will soon be released. Thank you for your issue.

**Comment by sobolewska** [comment]
ok, I can wait for a release with fix, as I wrote above i found a way to workaround.

**Comment by skyline-gleb** [comment]
Released [v1.6.0](https://github.com/2gis/Winium.Desktop/releases/tag/v1.6.0)
