### ISSUE TITLE
Support selenium grid

### ISSUE THREAD

**Issue by jalona** [2gis/Winium.Desktop#97]
Example:
```
start Winium.Desktop.Driver.exe --verbose --role node --hub http://localhost:4444/grid/register
```

**Comment by NickAb** [comment]
Some reference implementation is available in Winium.StoreApps https://github.com/2gis/Winium.StoreApps/blob/master/Winium/Winium.StoreApps.Driver/NodeRegistrar.cs

**Comment by skyline-gleb** [comment]
@jalona sorry, but using desktop.driver as grid node not supported and is not planned in the near future

**Comment by NickAb** [comment]
@jalona, you can try registering Winium.Desktop as grid node manually by sending json to grid/register/ endpoint of you grid server.
json should be somewhat similar to [this template](https://raw.githubusercontent.com/2gis/Winium.StoreApps/ad283b8c175eec5e1804a0c3109305f86d8b079a/Winium/Winium.StoreApps.Driver/template.nodeconfig.json)

Also, you can take a look at grid support in Winium.StoreApps at https://github.com/2gis/Winium.StoreApps/blob/master/Winium/Winium.StoreApps.Driver/NodeRegistrar.cs and try to port it. Pull Requests are welcomed!
