### ISSUE TITLE
Driver.GetPageSource(),gives error :"getPageSource is not valid or implemented command".

### ISSUE THREAD

**Issue by Pranodayd** [2gis/Winium.Desktop#98]
After using Driver.GetPageSource(),Winium.Desktop.Driver gives error :"getPageSource is not valid or implemented command".

**Comment by NickAb** [comment]
Unfortunately Winium.Desktop does not implement page source at the moment. To study and investigate UI tree of app under a test one can use UISpy or VisualUIAVerifyNative, or inspect from Windows Kits.

**Comment by Pranodayd** [comment]
Hi @NickAb .
I am using VisualUIAVerifyNative to view UI hierarchy of UAT.We have implemented custom checkpoints in Appium and Winium.StoreApps by parsing xml returned by Driver.getPageSource(); Same thing I am looking to implement in Winium.Desktop.I will try to look into it and implement the solution in Winium.Desktop project.

**Comment by NickAb** [comment]
Adding Gleb Golovin who is core developer on Winium.Desktop

**Comment by Pranodayd** [comment]
Hi @NickAb and @skyline-gleb .
I have implemented my solution without using Driver.getPageSource();
Winium.Desktop.Driver seems to be very slow in returning WebElement found using Xpath locator Strategy,and hence my checkpoint generation code takes lot of time to retrieve required information from controls present on the AUT's window.

In case of implementing my solution with the help of Driver.getPageSource(),will allow me to get the information very quickly as I will have to access the driver only once to get pageSource.Once I get .xml I can parse .xml quickly using Xpath.

Can we have getPageSource command implemented in Winium.Desktop soon?
Thanks.

**Comment by NickAb** [comment]
@skyline-gleb should be able to provide any estimates. But our teams are currently busy with main projects, so it might not be fast.

Generating full page source might be very slow too as currently driver includes all elements on desktop, so if you have any windows except AUT's windows open, then it will slow down page source. In fact it most likely what slows down your XPath.

If you can, please provide examples of XPath queries that you use, maybe we will be able to provide suggestions on how to optimise them by limiting scope, etc.

**Comment by Pranodayd** [comment]
@NickAb .I have limited the search to my application only by providing Starting node's @class attribute,a value which is unique to my Application Window,but still Winium.Desktop driver responds slowly.

**Comment by Pranodayd** [comment]
@NickAb .I have limited the search to my application only by providing Starting node's @class attribute,a value which is unique to my Application Window,but still Winium.Desktop driver responds slowly.

I thing Getting PageSource will be more efficient in response time as compared to what I am experiencing while retrieving data by submitting xpath queries to Winium.Desktop Driver.@skyline-gleb any estimate regarding PageSource implementation in Winium.Desktop?

**Comment by skyline-gleb** [comment]
Hi Pranodayd.
Get code example please. If you search with unique @class attribute from Driver, it's not speed-up search.
About page source implementation: sorry, i can not to give estimates now; I will write here, when there will be news.

**Comment by Pranodayd** [comment]
Hi @NickAb and @skyline-gleb 
Guys I could substantially reduce the time of finding elements using Xpath,by using FindChildElement command. :-) 
I used to find every element from root,which was taking hell lot of time.I changed my implementation to find element by running Xpath in the context of Parent Element.Which is working great!!!

**Comment by skyline-gleb** [comment]
that's cool

**Comment by NickAb** [comment]
Great to hear. Most likely you should be able to combine finding parent element and xpath into single find by xpath statement if needed. They key thing is to always limit scope as best as you can. Especially at top levels, as the driver can access whole desktop.

**Comment by Pranodayd** [comment]
Hi @NickAb  and @skyline-gleb .
Actually Appium does not support FindChildElement command with Xpath strategy.So I was having my code implemented without using it and I used to parse each element from root element.It works fast their as it executes queries against PageSource.xml.I came to know that Winium.Desktop supports FindChildElement with Xpath strategy and changed my implementation for Windows Desktop applications automation.Thanks a lot guys!!!

**Comment by congzhangzh** [comment]
Will this be implement even just useful for easy debug like inspect by appium-desktop inspect function?

**Comment by sszemer** [comment]
Will this ever be implemented?
Why is this issue closed?
Winium seems dead for a few years now :/
